#
# Github pages customized 
# for redroundrobin.site
#

title: "Red Round Robin"
description: >
  Sito ufficiale per il progetto di Ingegneria del software 2019-2020, Informatica, Università di Padova

author: Gruppo 6
email: redroundrobin.site@gmail.com
remote_theme: jekyll/minima@2.5-stable
show_excerpts: false


minima: 
  date_format: "%d %B %Y"
  social_links: 
    github: Maxelweb

header_pages: 
  - membri.md
  - contatti.md
